### ISSUE TITLE
Ability to use some repository keywords will vary based on support from the database

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#100]
This discussion started under #99 (see comments from @otaviojava) but is a much broader topic that isn't specific to that single pull.  Several repository keywords, including GreaterThan, GreaterThanEqual, LessThan, LessThanEqual, IgnoreCase, Between, Or? ... will be available from some databases but not others.  We should improve the specification and API in ways that are most helpful in conveying this information so that it is clear to users which keywords to rely on for the databases or types of databases used.

**Comment by otaviojava** [comment]
Let's take a step back on the Jakarta Data proposal. The main goal is to be data agnostic instead of looking only at a specific database type, such as a relational database.

Said that the Repository interface should have a more considerable cohesion around database types instead of going to a database type.

We have almost 400 database solutions in the market, and it would take a lot of work to keep and add support to those keyword databases.

I suggest exploring OOP in our favor. Therefore, the extensions like the market do with Spring and Jakarta NoSQL. Thus, CassandraRepository, MongoRepository, and so on.

So, allowing it to JPA creates its repository to put that specific behavior is a good solution to the API moving those to this specialization:

* https://github.com/jakartaee/data/pull/96
* https://github.com/jakartaee/data/pull/97
* https://github.com/jakartaee/data/pull/93
* https://github.com/jakartaee/data/issues/100
