### ISSUE TITLE
Simplify Repository annotation

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#144]
Hey, some points would be nice to clarify at the Repository annotation:

> This class is a CDI bean-defining annotation when CDI is available....

Can we remove this point? Once it is DI agnostic, it needs to make sense.

>  Jakarta Persistence and Jakarta NoSQL define entity models you may use in Jakarta Data.

It is also not true; I can use JSON-B with Webservice, for example.

I prefer to keep the first two paragraphs because the other details are on the spec page.

**Comment by njr-11** [comment]
> > This class is a CDI bean-defining annotation when CDI is available....
> 
> Can we remove this point? Once it is DI agnostic, it needs to make sense.

Removing that would worsen the user experience for CDI because it could require the user to take extra steps to enable their application for CDI.  It doesn't have any impact on custom dependency injection because it is written to only apply "when CDI is available".  Instead of removing, we should reword it or add language that makes it more clear, such as calling out the validity of custom dependency injection as well as CDI.


> > Jakarta Persistence and Jakarta NoSQL define entity models you may use in Jakarta Data.
> 
> It is also not true; I can use JSON-B with Webservice, for example.

It is incorrect logic to conclude that being able to use Jakarta Persistence and Jakarta NoSQL entities means that you cannot use other types as well.  It doesn't say that.  However, it would be fine if it helps for clarity to add more wording here that mentions the validity of other entity models.
