### ISSUE TITLE
Should we have support to configuration

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#22]
Once we're talking about data sources, it is natural to have settings such as user, password, and so on.

My question is: should we have support or a convention about configuration on this version?

#### JPA

```properties
# datasource configuration
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = hibernate
quarkus.datasource.password = hibernate
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/hibernate_db

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
```

#### Mongodb

```properties
# configure the mongoDB client for a replica set of two nodes
quarkus.mongodb.connection-string = mongodb://mongo1:27017,mongo2:27017

# configure the mongoDB client for a single instance on localhost
quarkus.mongodb.connection-string = mongodb://localhost:27017
```

#### JPA

```properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpass
spring.datasource.url= jdbc:mysql://localhost:3306/myDb?createDatabaseIfNotExist=true
```

#### MongoDB
```properties
spring.data.mongodb.uri=mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
spring.data.mongodb.database=mygrocerylist
```

#### JPA

```properties
jpa.default.properties.hibernate.hbm2ddl.auto= update
jpa.default.properties.hibernate.hbm2ddl.show_sql=true
```

**Comment by njr-11** [comment]
+1 to supporting configuration.
We also need to consider that in a Jakarta EE environment, many users of relational databases/Jakarta Persistence are using data sources either configured by vendor-specific means or [DataSourceDefinition](https://jakarta.ee/specifications/platform/10/apidocs/jakarta/annotation/sql/datasourcedefinition), and are possibly accessed through resource references, and possibly with support for forms of authentication beyond just basic user/password.  The granularity of some of these existing definitions concerns me (for example java:comp names that mean different things based on which component does the lookup) with respect to a repository that is shared across the whole application or even multiple applications.

There could also be multiple data sources and/or multiple Jakarta NoSQL providers pointing at different databases, so configuration might be needed on a per-repository basis rather than system wide (although the latter would certainly be more convenient).

I wonder if we should have a way to configure a system-wide default for relational and default for NoSQL, and then additional configurations that repositories could optionally point at if not wanting the default.

Configuration will be a difficult area to get right, but an important one.

**Comment by keilw** [comment]
We shall use Jakarta Configuration once that produced a Final Release or at least Stable Milestone.

**Comment by graemerocher** [comment]
This seems beyond the scope IMO and is a slippery slope given how many different databases and use cases are out there

**Comment by gavinking** [comment]
I agree with @graemerocher on this. I think this is out of scope for a "repository" spec, would offer little real portability, and risk making configuration even more complicated.

**Comment by otaviojava** [comment]
Ok, I will close this issue as it won´t fix it.
