### ISSUE TITLE
explain how repositories work (or not) with entity lifecycle and persistence contexts

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#224]
The spec does not mention the idea that an entity might have some sort of persistent lifecycle, nor does it mention the concept of a persistence context.

This hole is big enough to navigate an imperial star destroyer though, since there's a deep, fundamental difference in the programming model between:

- persistence context-free approaches, where updates require explicit API calls, and
- a solution like Jakarta Persistence, where updates are implicit, detected by the persistence context via dirty checking, and asynchronous.

It's impossible to imagine an API which abstracts over this difference!

Therefore, Jakarta Data needs to explain which of these programming models applies to a `CrudRepository`.

If the answer is that a `CrudRepository` is only useful with persistence context-free programming models, then the specification should face up to the fact that Jakarta Data is _not_ compatible with the Jakarta Persistence API, where every `EntityManager` is tied to a persistence context.

Now, you might be lucky, because I have proposed that Jakarta Persistence add a `StatelessEntityManager`, which would have no persistence context, but we have _not_ currently targeted this for JPA 4.0, because we want to take our time to get this functionality right.

On the other hand, if `CrudRepository` _is_ supposed to be used with a persistence context, the spec needs to explain how that works.

**Comment by gavinking** [comment]
OK, so over in the discussion of #229, it's clear that there's overwhelming hostility to saying anything about persistence contexts and entity lifecycle, or toward engaging directly with concepts in the Jakarta Persistence spec.

If that's a correct understanding of the situation, then Jakarta Data should simply _remove_ references to Jakarta Persistence from the specification, and top claiming to support JPA.

**Comment by Sanne** [comment]
This issue is critical: when dealing with managed entities in JPA, the scope of changes is tied to the transaction boundaries rather than the imperative operations a user would invoke on a repository.

This completely changes the semantics and has deep implications on how one designs the entire application, so if this isn't precisely defined by the spec it fundamentally violates the goal of the spec: introducing a "persistence agnostic API":
I would need to significantly rewrite and rethink my application when changing small details of the underlying persistance setup, so having this under-specified and still allow the application to compile just fine with the highly abstract API would mislead developers, most likely result in catastrophic problems at runtime.

So it's important to specify this aspect accurately, otherwise the promise of providing a general abstraction becomes a liability rather than a feature.

The problem is further exacerbated by the fact that binding to a transactional scope is happening only when "[When running in an environment where Jakarta Transactions is available and a global transaction is active on the thread of execution for a repository operation and the data source backing the repository is capable of transaction enlistment](https://jakarta.ee/specifications/data/1.0/data-1.0.0-b3#_jakarta_transactions_usage)"
which again seems promise portability while changing the semantics of operations quite drastically:
code which is meant to run w/o a transaction needs to be designed differently than code which is meant to be run with a  transaction; not only the code but the whole application might need to be designed differently.


> If that's a correct understanding of the situation, then Jakarta Data should simply _remove_ references to Jakarta Persistence from the specification, and stop claiming to support JPA.

+1 

I'd love to help here, but honestly I'm not sure how to solve this problem without compromising the proposed abstraction; like @gavinking mentions above, the only sane option coming to mind would be to fully decouple from JPA, aka to not allow using managed entities with such an API.

One could possibly still leverage libraries like Hibernate by using their stateless imperative capabilites which bypass the notion of managed entities, however such capabilities are limited: many non-trivial applications require a persistence context, and are better off with managed entities, but perhaps that's not the target of this spec.

HTH

**Comment by otaviojava** [comment]
@njr-11 could you take this one?

**Comment by njr-11** [comment]
> @njr-11 could you take this one?

I'm out of the office over the next couple of days, with limited time to spend on Jakarta Data, but can look at it afterward.  With all that's going on, I'll try to at least attend this week's Jakarta Data call.  In the mean time, it will be good for the spec community to be able to continue to discuss their thoughts on this issue and some of the others that were more recently opened, so that hopefully we will know where everyone is at when we look into proposing solutions.

**Comment by lprimak** [comment]
> I'd love to help here, but honestly I'm not sure how to solve this problem without compromising the proposed abstraction; 

From users' perspective, I would think that this would make the data spec very hard to swallow.
IMHO a simple annotation parameter enum could 'couple' to the transaction without breaking anything, for example

**Comment by Sanne** [comment]
> From users' perspective, I would think that this would make the data spec very hard to swallow.

I agree, that's why I'm cautioning about this and suggesting to not use JPA as a lower layer: it would have implications beyond the data layer and go against principles of encapsulation, reuse and safe composition in larger applications.

> IMHO a simple annotation parameter enum could 'couple' to the transaction without breaking anything, for example

Sorry but I don't really undersand how that would help, could you elaborate please. I hope you know JPA will manage entities once it has loaded them? This means it has implications on all semantics of code interacting with it, and it's not interchangeable with another datastore technology which does not manage entity lifecycles w/o fundamentally rethinking how the data layer is integrated. I don't think that adding [removing] an annotation will suffice when users need to reconsider all interactions with the database.

**Comment by lprimak** [comment]
See https://github.com/jakartaee/data/issues/264

The way I see Jakarta Data "common use-case" is from the current Jakarta EE / JPA user's perspective. Something that works like DeltaSpike Data.
From that perspective, `CrudRepository` that just returns unmanaged entities is not really useful since it only provides read-only view of the entity (which is mutable). In order to start updating the entity, you would have to use something like `em.merge()` which brings more complexity.

I propose to add an annotation that would make `CrudRepository` return a managed entity and would use the current JPA Transaction context to do it. This would not couple the user to JPA if they don't want that, but for the major JPA use case, this should work like DeltaSpike and Spring Data does.
