### ISSUE TITLE
Create a blueprint of the TCK

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#26]
Now that Jakarta EE specs have the ability to develop TCKs outside of the main TCK repository I think it would be a good idea to create a blueprint for how we want the TCK to operate. 
Having a blueprint in place early and having builds set up to create snapshot artifacts in the Jakarta stagging repository will allow implementors quick and easy access to test their implementations. 

Things to consider: 
- Do tests need to run inside of a Web or EJB container, or can they be written as standalone tests? 
- What test platform should we use? JUnit4/JUnit5/TestNG?
- What database(s) will users need for testing?  Or do we need to somehow create mock in-memory databases?
- How will we implement Signature Testing and how can we automate the creation of signature test files?

I think getting this set up as soon as possible will help the development of the spec since we will be able to write tests alongside updates to the API. I'm willing to help set this up 😄

**Comment by njr-11** [comment]
I recommend targeting as many of our TCK tests as possible to run against the Jakarta EE core profile, which will put us into the right position to get Jakarta Data included into core if Jakarta Data is wanted in that profile, which I suspect will be the case because MicroProfile had expressed some interest in a Data specification if Jakarta hadn't started one.

That said, we will also need some tests to run under Jakarta EE web profile in order to test proper integration with specifications like Jakarta Transactions and Jakarta Persistence.

**Comment by KyleAure** [comment]
Thanks for the feedback everyone.  I am going to get started working on getting a blueprint put together and testing some options out. 
There is a bigger Jakarta discussion happening right now around standardizing/modernizing the standalone TCKs.
https://www.eclipse.org/lists/jakartaee-tck-dev/msg01731.html

There have been no decisions thus far on what technologies/frameworks are required. So I will take the safe approach and use the following: 
1. JUnit5 (testing framework)
2. Arquillian (integration testing framework)
3. java.util.logging (logging framework)
4. sigtest-maven-plugin (signature testing)

As mentioned before I will figure out a way to put tests into one of three groups (standalone, core profile, web profile) where: 
1. Standalone tests are only run against an available service provider.
2. Core profile tests run on core/web/full profile servers. 
3. Web profile tests run on web/full profile servers.
