### ISSUE TITLE
Does make sense rename Limit to Range?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#35]
To make the intention of the ```Limit``` class more explicit, what do you think if we rename it to ```Range``` instead?

## Quarkus
E.g.: 

https://quarkus.io/guides/hibernate-orm-panache#using-a-range-instead-of-pages

```java
Range range = Range.of(2);

Range range = Range.of(2, 10);
```

**Comment by njr-11** [comment]
Limiting results to within a range is one of several patterns that are intended to be provided by `Limit`, so I'd say just rename the `of(long, long)` method to reflect the intent,

```
public static Limit range(long startAt, long endAt);
```

But leave the `Limit.of(maxResults)` as it is, because that better reflects the usage pattern to limit the quantity of results.

There is a third pattern that I envision for Limit as well, which is an advanced/more customized form of pagination that eliminates the possibility of duplicate entries being returned across pages due to the risk of the data being added/removed simultaneously by another user.  It would look something like,

```
for (Employee[] page = null; page == null || page.length > 0; ) {
    page = employees.findByStatusAndIdGreaterThanOrderById(
                    "FULL TIME",
                    page == null ? -1 : page[page.length-1].getId(),
                    Limit.of(100));
    ...
}
```

This pattern is not a range either.

**Comment by beikov** [comment]
>There is a third pattern that I envision for Limit as well

This is commonly referred to as "keyset pagination" which I implemented in Blaze-Persistence on top of JPA. Being able to extract `previousPageable` and `nextPageable` from a `Page` or `Slice` (like Spring Data allows it) would allow to nicely model this i.e.

```java
    page = employees.findAllByStatus(
                    "FULL TIME",
                    page == null ? PageRequest.of(100) : page.nextPageable()
    );
    ...
```

With custom `Page` and `Pageable` implementations, the details can be left to the underlying implementation.

You can find some details about this here: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#anchor-keyset-pagination

**Comment by njr-11** [comment]
I updated the method name for creating range limits under #38 and have opened a separate issue #39 from @beikov 's comment to allow/enable keyset pagination.
