### ISSUE TITLE
Keyset pagination

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#39]
@beikov originally added this comment under #35, but it's worth an issue of its own.  While the provider will implement `Page` and the `nextPageable` and `previousPageable` that are obtained from it, I'd prefer that we look into whether keyset pagination can be specified in a more standard way if possible rather than relying on particular vendors to possibly provide it.

> This is commonly referred to as "keyset pagination" which I implemented in Blaze-Persistence on top of JPA. Being able to extract `previousPageable` and `nextPageable` from a `Page` or `Slice` (like Spring Data allows it) would allow to nicely model this i.e.

```java
    page = employees.findAllByStatus(
                    "FULL TIME",
                    page == null ? PageRequest.of(100) : page.nextPageable()
    );
    ...
```

> With custom `Page` and `Pageable` implementations, the details can be left to the underlying implementation.

> You can find some details about this here: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#anchor-keyset-pagination

_Originally posted by @beikov in https://github.com/jakartaee/data/issues/35#issuecomment-1268066903_

**Comment by beikov** [comment]
I guess it might be worth adding something like a `KeysetAwarePage` and `KeysetPageable` to the API which provide additional details about the keyset parts. Another concept that could be interesting is a `KeysetCursor` which I called simply `Keyset` in Blaze-Persistence. A `KeysetCursor` would encapsulate values of an object, by which objects are sorted.

For example, when we query for `Cat` and `order by name, id desc`, we might get:

|name|id|
|------|--|
|A|2|
|A|1|
|B|3|

So the `KeysetCursor` of every object is the tuple `(name,id)` because that is what is ordered by.

A `KeysetAwarePage` contains at least 2 such cursors for the first and the last element, which serve as the basis for the previous and next `KeysetPageable` through `previousPageable` and `nextPageable`. For GraphQL Relay pagination it is necessary to attach a cursor to every object, so it might be worth adding optional support for accessing a list of cursors.

**Comment by otaviojava** [comment]
I like the idea, but I am unsure if it will work on other data sources.
Maybe it specializes in JPA.

**Comment by njr-11** [comment]
I wonder if all we need on the API is an indicator of whether or not to use keyset pagination, along with making the Pageable constructor protected rather than private so that implementations can supply a keyset-aware Pageable on the return from page.next/previous.  The `OrderBy` is either already known from the repository method itself (or if it's a custom `@Query` then I'd say repository-provided keyset support doesn't apply because in that case the user owns the entire query and does not want it tampered with).  The keyset values are already known from the `Page<EntityClass>` last result (for next) and first result (for previous).

```
Page<Person> page1 = people.findBy...OrderByLastNameAscFirstNameAscIdAsc(
                     ..., // query parameters
                     Pageable.of(50).withKeyset());

Page<Person> page2 = people.findBy...OrderByLastNameAscFirstNameAscIdAsc(
                     ..., // same query parameters
                     page1.nextPageable());
```

In this case, requesting subsequent pages looks no different from normal pagination, and the only details for the user are to add the keyset indicator onto the initial Pageable and include all the desired keyset attributes in the OrderBy.  I'm interested in giving this a try and experimenting with it more once the Page/Slice API is further along.

**Comment by beikov** [comment]
>I wonder if all we need on the API is an indicator of whether or not to use keyset pagination, along with making the Pageable constructor protected rather than private so that implementations can supply a keyset-aware Pageable on the return from page.next/previous.

Yes, that's exactly what I had in mind and how I implemented this so far for Blaze-Persistence in the Spring Data integration.

>Repository providers are likely to want the information well before that in if they want to prepare the queries for keyset pagination in advance

I doubt that's really possible with a dynamic order by. Anyway, providers could cache queries internally based on the final `Sort`,  but I don't think an additional annotation is necessary.

**Comment by njr-11** [comment]
> I doubt that's really possible with a dynamic order by. Anyway, providers could cache queries internally based on the final `Sort`, but I don't think an additional annotation is necessary.

I've been trying as best I can to have the spec encourage static OrderBy wherever it is possible.  I would think static would make the most sense for keyset because the user will want to know that information upfront to prepare indexes in the database.  I don't particularly like the idea of this extra annotation either.  It was the first thing I could think of for statically specifying.

Another way could be to actually define a `KeysetPageable` interface that could be declared as the pagination parameter to the repository method, where maybe a `Pageable.size(50).withKeyset()` could create a `KeysetPageable`.

```
Page<Person> findBy...OrderByLastNameAscFirstNameAscIdAsc(..., KeysetPageable pagination);
```

The problem here is that the signature for `page.nextPageable()` needs to return normal `Pageable` and so even if we return a `KeysetPageable` subclass, the user would need to cast it to `KeysetPageable` just to invoke their repository method to get subsequent pages.  But because that cast will be seen as awkward/annoying, it's likely users would switch the repository method signature back to `Pageable`, which would still work but entirely defeat the purpose because it isn't specified statically anymore.  So I like this second possibility even less than having the annotation.  We could probably solve that with `page.next/previousKeysetPageable` but that is even more unnecessary divergence/duplication. Hopefully there is another way of statically specifying that we will be able to think of.

**Comment by njr-11** [comment]
> Don't you think that this kind of paging is rare? I mean who writes in their code
> 
> ```java
> Page<Person> page = repository.findByAbc(Pageable.size(50).withKeyset());
> Page<Person> nextPage = repository.findByAbc((KeysetPageable) page.nextPageable());
> ```
> 
> I'd rather expect that the `Pageable` is constructed through some standard means and the `nextPageable`/`previousPageble` methods are mostly only invoked for purposes of generating a URL for clients.

It is my understanding that keyset pagination only works properly when going sequentially to the next or previous page, so `nextPageable`/`previousPageable` is the pattern that I was proposing (minus the need to cast).  It would help if you can provide a more complete example of the usage pattern that you see being most common/useful because I likely don't have a correct understanding of it.

I suppose a `KeysetCursor` could allow a statically specified approach:
```
Page<Person> findBy...OrderBy...(..., Pageable pagination, KeysetCursor cursor);
```
along with `page.keysetCursor()` but it seems like more unnecessary burden on the user to keep track of both and avoid mixing pagination that is more distant with a cursor that is only useful for the next or previous.

Another possibility that's probably about as good as the annotation could be including `WithKeyset` in the `find...By`,
```
Page<Person> findWithKeysetBy...OrderBy...(..., Pageable pagination);
```

**Comment by beikov** [comment]
I think that users generally don't use the `Pageable` instances created by `nextPageable`/`previousPageable` in another repository call. These methods are IMO mostly interesting for generating URLs.

I suppose most users will use an HTTP endpoint similar to this:

```
@GET
public Page<Person> findAll(KeysetPageable pageable) {
    return repository.findAll(pageable);
}
```

The `KeysetPageable` will be created by a JAX-RS integration based on query parameters. In case of GraphQL it will be sourced from query arguments etc.
Now, the integration with these endpoint technologies will usually also translate the `page.previousPageable()`/`page.nextPageable()` results into e.g. HTTP headers or some special fields in the result payload, in a form such that it can deserialize it again.

My point here is, the user will use the type `KeysetPageable` in his/her API and the integration will deserialize to that type. A user usually won't even call `page.previousPageable()`/`page.nextPageable()` in their own code.

A `KeysetCursor` on its own is not very helpful, because you also need to specify if you want results before or after the cursor. I guess it might make sense to have `KeysetCursor` expose `previousPageble()` and `nextPageable()` methods though.

**Comment by otaviojava** [comment]
@beikov sorry for the delay, e.g., Cassandra does not have the ```OR``` indicator: https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#select-statement


Cassandra works with token instead.

**Comment by beikov** [comment]
Why do you need an OR connector? Keyset pagination works with simple tuple comparison which Cassandra appears to have.

**Comment by otaviojava** [comment]
Hum, I got you point. 
Thanks

**Comment by njr-11** [comment]
I agree the HTTP scenario is likely more common. Often it will be less critical to avoid duplicates/misses, but not always, so let's aim to cover both scenarios for keyset pagination.

Let's keep `KeysetPageable`, which can accept the dynamically constructed requests and also serve as the indicator for when keyset pagination is wanted.
```
Page<Person> findBy...OrderByLastNameAscFirstNameAscIdAsc(..., KeysetPageable pagination);
```

It could be constructed with an ordered list of key values for the last (or first) entry of the prior page, in either a forward or reverse direction,
```
KeysetPageable pagination = Pageable.size(50).withNextKeyset(previousKeyValues...) // can leave empty for first
KeysetPageable pagination = Pageable.size(50).withPreviousKeyset(nextKeyValues...)
```

Example of initial usage:
```
Page<person> page1 = people.findBy...OrderByLastNameAscFirstNameAscIdAsc(
    ...,
    Pageable.size(50).withNextKeyset());
```

Example of forward direction:
```
Person last = page1.get(page1.getNumberOfElements() - 1);
Page<person> page2 = people.findBy...OrderByLastNameAscFirstNameAscIdAsc(
    ...,
    Pageable.size(50).withNextKeyset(last.lastName, last.firstName, last.id));
```

Example of reverse direction:
```
Person first = page25.get(0);
Page<person> page24 = people.findBy...OrderByLastNameAscFirstNameAscIdAsc(
    ...,
    Pageable.size(50).withPreviousKeyset(first.lastName, first.firstName, first.id));
```

And we could also include these for convenience for the scenarios that sequentially read through results,
```
page.nextKeysetPageable()
page.previousKeysetPageable()
```

As for the relationship between Pageable and KeysetPageable, I've been wondering about the `getPage()` method inherited from Pageable that returns a page number, and whether page numbers make sense for keyset pagination.  For example, if you started and went forward a few pages and then results were added with a smaller id, you could end up with a page 0 or even negative page numbers which are currently disallowed by Pageable.  Would it make sense for us to have `getPage` raise `UnsupportedOperationException` for KeysetPageable and consider the keyset pages unnumbered?

**Comment by beikov** [comment]
>Let's keep KeysetPageable, which can accept the dynamically constructed requests and also serve as the indicator for when keyset pagination is wanted.

Sounds good to me. I'd like to point out the implication of this, which is that the `KeysetCursor` of a `KeysetPageable` might be null then, in which case the fallback to offset based pagination is necessary.

I'd like to suggest naming the methods `beforeKeyset` and `afterKeyset` instead of `withPreviousKeyset` and `withNextKeyset`, as that looks nicer to me.

>And we could also include these for convenience for the scenarios that sequentially read through results,

Sounds reasonable.

>As for the relationship between Pageable and KeysetPageable, I've been wondering about the getPage() method inherited from Pageable that returns a page number, and whether page numbers make sense for keyset pagination. For example, if you started and went forward a few pages and then results were added with a smaller id, you could end up with a page 0 or even negative page numbers which are currently disallowed by Pageable. Would it make sense for us to have getPage raise UnsupportedOperationException for KeysetPageable and consider the keyset pages unnumbered?

Page numbers are an approximation and the quality of that, as you noticed, depends on how much data is inserted/deleted prior to the "current page". In the implementation in Blaze-Persistence, I treat the request for the first page specially. Since every `KeysetPageable` also always contains a page number, we know when the first page is requested. When the first page is request, we simply don't use the keyset cursor, but just run the query with a limit.

Any thoughts on adding a `KeysetAwarePage` that provides access to the `KeysetCursor` of the elements on the page?

**Comment by njr-11** [comment]
> I'd like to suggest naming the methods `beforeKeyset` and `afterKeyset` instead of `withPreviousKeyset` and `withNextKeyset`, as that looks nicer to me.

I like `beforeKeyset` and `afterKeyset`. Those are more descriptive names and also more concise!

> Any thoughts on adding a `KeysetAwarePage` that provides access to the `KeysetCursor` of the elements on the page?

This prompted me to think about the `Page` vs `Slice` discussion that happened under a separate issue where another spec participant pointed out the need for the distinction and requirement for `Page` to pre-emptively capture a count of the total number of results across all possible pages, whereas `Slice` is unaware of a total number of results.  The concept of `Slice` seems to me like a much better fit for keyset pagination, and having a separate class for `KeysetAwarePage` that inherits from `Slice` but not normal `Page` could allow us to avoid pre-emptively querying for a total number of results.  It could also be a better signal for requesting keyset pagination, which would let users write the repository method in terms of just `Pageable` and avoid the extra call to an empty `.afterKeyset()` on the initial request.  A `KeysetAwarePage` could even override the `nextPageable` to return the more specific type `KeysetPageable` which would make `nextKeysetPageable` (and likewise for previousKeysetPageable) completely unnecessary.  So yes, this seems like a great idea.  I'd love to have a shorter name for it than `KeysetAwarePage` but cannot think of much else besides `KeysetPage` which aligns well with `KeysetPageable` but isn't as properly descriptive as `KeysetAwarePage`.

**Comment by beikov** [comment]
IMO the extraction of the page count is an orthogonal matter. In Blaze-Persistence we also have a `KeysetAwareSlice`.

So I'd like to suggest the following types:

```
interface Pageable {
    // existing methods...
    KeysetPageable afterKeyset(Object... keyset);
    KeysetPageable beforeKeyset(Object... keyset);
}
interface KeysetCursor {
    int size();
    Object getKeysetElement(int index);
}
enum KeysetMode {
    NEXT,
    PREVIOUS
}
interface KeysetPageable extends Pageable {
    KeysetCursor getKeysetCursor();
    KeysetMode getKeysetMode(); 
}
interface KeysetAwareSlice<T> extends Slice<T> {
    KeysetPageable nextPageable();
    KeysetPageable previousPageable();
    List<KeysetCursor> getKeysetCursors();
}
interface KeysetAwarePage<T> extends Page<T>, KeysetAwareSlice<T> {
}
```

**Comment by njr-11** [comment]
Is `List<KeysetCursor> getKeysetCursors()` redundant?
I can see someone using it with a loop to find the cursor,
```
KeysetCursor forwardCursor = null;
for (KeysetCursor cursor: page.getKeysetCursors())
    if (KeysetMode.NEXT.equals(cursor.getKeysetMode())) {
        forwardCursor = cursor;
        break;
    }
```

but the same can be achieved more directly with,
```
KeysetCursor forwardCursor = page.nextPageable().getKeysetCursor();
```

I also wonder if we could simplify `KeysetCursor` to just being a keyset `Object[]`, which has the same ability to obtain `.length` and a particular key value by its index and also the advantage that you can send the keyset directly to the `afterKeyset` and `beforeKeyset` methods without any conversion back and forth.

```
interface KeysetPageable extends Pageable {
    Object[] getKeyset();
    KeysetMode getKeysetMode(); 
}
interface KeysetAwareSlice<T> extends Slice<T> {
    KeysetPageable nextPageable();
    KeysetPageable previousPageable();
}
```

> IMO the extraction of the page count is an orthogonal matter.

I agree it needs to first be determined under the separate open issue for adding Page/Slice exactly what will be added to Jakarta Data in that space.  After that I do think it is worth assessing whether a pattern with pages/results counted in advance (if that is added) makes any sense for keyset pagination and whether keyset pagination should be aligned with just one of (Slice vs Page) or both.

**Comment by beikov** [comment]
>Is List<KeysetCursor> getKeysetCursors() redundant?

The purpose of this method is to be able to access the keyset cursors of all results, not just the first and last. The main usefulness is for implementing the GraphQL Relay specification, which needs the cursor for every "edge", which is a wrapper around the actual data item.

>I can see someone using it with a loop to find the cursor,

That code won't work, but your thoughts are almost correct in the sense that there is some "redundancy" because:

`getKeysetCursors().get(0) == previousPageable().getKeysetCursor()`

and

`getKeysetCursors().get(getKeysetCursors().size() - 1) == nextPageable().getKeysetCursor()`

>I also wonder if we could simplify KeysetCursor to just being a keyset Object[], which has the same ability to obtain .length and a particular key value by its index and also the advantage that you can send the keyset directly to the afterKeyset and beforeKeyset methods without any conversion back and forth.

That surely is an option, but I personally prefer having a dedicated type `KeysetCursor` which frameworks can implement and control stuff like serialization.

**Comment by beikov** [comment]
>Good point, I wasn't thinking of GraphQL. It should be fine to keep this method and non-GraphQL users can just skip over it.

Yep 👍 

>Could KeysetCursor end up adding complexity to deserialization? It would require having the vendor's KeysetCursor implementation class available on the class loader for deserialization, whereas an Object[] of what are likely String or primitives or Java primitive wrappers like Integer ought to be easily serializable/deserializable independent of class loader availability.

Serialization always adds some complexity 😄 

I don't have a perfect answer for what is better, but I really believe that a named type that encapsulates the contents of a keyset and hides the mutable array is just better design-wise. Otherwise an implementation that returns the array would constantly have to copy the array to be safe.

**Comment by keilw** [comment]
> Good point, I wasn't thinking of GraphQL. It should be fine to keep this method and non-GraphQL users can just skip over it.

@njr-11 In that case non-GraphQL users or implementations shouldn't be forced to implement something they don't need.
Jakarta NoSQL has a granularity like

- [communication-column](https://github.com/eclipse-ee4j/nosql/tree/main/api/communication/communication-column)
- [comunication-document](https://github.com/eclipse-ee4j/nosql/tree/main/api/communication/communication-document)
- [communication-key-value](https://github.com/eclipse-ee4j/nosql/tree/main/api/communication/communication-key-value)

And while the spec may still require more work there to ensure such modularity is possible (especially for the TCK) the same should apply here. If certain elements of the API are not useful for certain types of databases, e.g. users of JPA or other NoSQL systems like MongoDB, etc. then GraphQL "stuff" must be modularized the same way. Either its own interface or a subclass, sub-interface, not in a general element.

**Comment by keilw** [comment]
I added a label [nosql](https://github.com/jakartaee/data/labels/nosql) here, feel free to adjust or add to other issues where approriate. Also created another **jpa** one.

**Comment by beikov** [comment]
Access to all `KeysetCursor` of all elements might not be super useful for use cases other than GraphQL Relay, but since extraction of keysets for the first and last elements has to be done already, it's IMO not a big deal to also implement extraction of keyset for the intermediate elements. I don't know what this has to do with JPA or NoSQL i.e. this is general purpose.

**Comment by keilw** [comment]
Can you point to a real use of GraphQL with traditional SQL/JPA kind of persistence?
I know it gets popular with NoSQL data sources, e.g. [rise-of-gql-db](https://dgraph.io/blog/post/rise-of-gql-db/) talks about NoSQL only and I have not seen it used with relational databases, but please anyone who knows about it explain.

[Spring GraphQL](https://docs.spring.io/spring-graphql/docs/current/reference/html/) is also an extension to Spring Data and not part of the "core" data framework, this sounds like a similar case, also same about 

> The KeysetPageable will be created by a JAX-RS integration based on query parameters. In case of GraphQL it will be sourced from query arguments etc.

Otherwise what kinds of mandatory prerequisites do we add to this spec?

- Jakarta REST
- GraphQL
- ...

**Comment by keilw** [comment]
> Access to all KeysetCursor of all elements might not be super useful for use cases other than GraphQL Relay

Then such method(s) don't belong to the "core" API, but should be in a GraphQL specific extension or implementation of API elements like Pageable.

**Comment by beikov** [comment]
>Can you point to a real use of GraphQL with traditional SQL/JPA kind of persistence?

I know a few companies that use GraphQL on top of Blaze-Persistence, but not sure if I can disclose that.

>I found some GraphQL usage in [Blaze Persistence](https://github.com/Blazebit/blaze-persistence/tree/main/integration), but each of these modules are implementation-specific, e.g. EclipseLink and various versions of Hibernate.

I am the author of Blaze-Persistence, and the various integration modules are orthogonal, and aren't JPA provider specific.

>The KeySetAwareSlice (unlike the Keyset itself) is not anywhere in the "core" API of [BP](https://www.javadoc.io/doc/com.blazebit/blaze-persistence-core-api/latest/allclasses-index.html), so which integration does it belong to? I suspect one of the Spring integrations, but where is the requirements to define Slice here?

The `KeysetAwareSlice` is part of the Spring Data integration, because that tries to integrate with the existing ecosystem and make it as easy as possible for users to get started. I didn't bother to create a custom data API as I was waiting for exactly this project, Jakarta Data.

>but where is the requirements to define Slice here?

A `Slice` is like a `Page` but without a page count. Wouldn't you think that this is a useful abstraction? I personally like it, but AFAIU there is a different issue that discusses that part.

>Then such method(s) don't belong to the "core" API, but should be in a GraphQL Relay specific extension or even subject to implementations.

The problem is, that keyset extraction is something that can be done more or less easily by the implementation, but it's very hard for an external consumer like an extension to do. Keyset extraction needs to be done anyway at least for the first and last element of a page/slice, so why not also offer a way to access the keyset of other elements?

**Comment by beikov** [comment]
Yeah, that would be fine for me. To avoid misunderstandings, you are proposing the following interfaces, right?

```java
interface Pageable {
    // existing methods...
    KeysetPageable afterKeyset(Object... keyset);
    KeysetPageable beforeKeyset(Object... keyset);
}
interface KeysetCursor {
    int size();
    Object getKeysetElement(int index);
}
enum KeysetMode {
    NEXT,
    PREVIOUS
}
interface KeysetPageable extends Pageable {
    KeysetCursor getKeysetCursor();
    KeysetMode getKeysetMode(); 
}
interface KeysetAwareSlice<T> extends Slice<T> {
    KeysetPageable nextPageable();
    KeysetPageable previousPageable();
    KeysetCursor getKeysetCursor(int index);
}
interface KeysetAwarePage<T> extends Page<T>, KeysetAwareSlice<T> {
}
```

**Comment by njr-11** [comment]
Yes, that looks good.   With 5 new keyset-related classes, I suppose we should consider if there should be a `jakarta.data.keyset` or `jakarta.data.repository.keyset` package for all of this, or if we should just keep it in `jakarta.data.repository` along with everything else.  Or another approach could be putting KeysetCursor and KeysetMode underneath KeysetPageable, as KeysetPageable.Cursor and KeysetPageable.Mode.  But that's all minor detail.  The overall design here seems pretty solid and should cover collecting all the information that is needed for keyset pagination in a way that parallels very closely with how non-keyset pagination is done and I think should seem familiar and intuitive to users.  I'll plan to do some experimentation with it in a mock up that we have of some parts of Jakarta Data to help verify.
