### ISSUE TITLE
[clarification]: is @OrderBy really allowed in combination with key-based pagination

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#508]
### Specification

@OrderBy annotation, key-based pagination

### I need clarification on ...

whether this actually works.

### Additional information

Correct me if I'm wrong, but I'm pretty sure this can't work:

> When multiple `OrderBy` annotations are specified on a repository method, the precedence for sorting follows the order in which the `OrderBy` annotations are specified, and after that follows any sort criteria that is supplied dynamically by `Sort` parameters, any `Order` parameter, or by a `PageRequest` parameter with sorting criteria.

I have not thought about it very hard, and perhaps I'm just being dense, but it seems to me that in key-based pagination, the key must define the complete ordering of the query. I think it breaks pagination to _prepend_ additional ordering criteria to the key. And _appending_ would be have no effect, since the key must be a unique key and determine a total order.

Is that right, or am I just being stupid?

**Comment by njr-11** [comment]
I don't see the problem here (and yes we have implemented this already and works fine).  It shouldn't matter where the ordering is defined, whether all from one source or a combination of static + dynamic.  Also note that OrderBy from the annotation is no different than OrderBy from the Query-by-Method-Name OrderBy keyword.  Both define ordering statically.  This ordering takes precedence, and after that, and dynamically specifying Sort criteria is applied.

Here is an example with keyset cursor based pagination,

```
KeysetAwareSlice<Employee> findBySalaryLessThanOrderByLastNameAsc(float maxSalary, PageRequest<Employee> pageReq);
```

```
PageRequest<Employee> pageRequestA = Order.by(_Employee.firstName.asc(), _Employee.id.asc())
                                          .pageSize(20)
                                          .afterKeyset("Doe", "John", 1000);

sortedByLastAndFirstNamesAndId = findBySalaryLessThanOrderByLastNameAsc(100000.0f, pageRequestA);

PageRequest<Employee> pageRequestB = Order.by(_Employee.id.asc())
                                          .pageSize(20)
                                          .afterKeyset("Doe", 1000);

sortedByLastNameAndId = findBySalaryLessThanOrderByLastNameAsc(100000.0f, pageRequestB);
```

**Comment by gavinking** [comment]
So if your static order is `@OrderBy("title")` and then you request key-based pagination based on `_Book.isbn`, which is equivalent to `order by title, isbn` in SQL, and then you apply the restriction `isbn>lastPageIsbn`, you get back well-defined pages? To me it seems like the order by `title` would break that.

**Comment by gavinking** [comment]
Or do you automatically add the `title` to the restriction and to the `Cursor`?

**Comment by njr-11** [comment]
> So if your static order is `@OrderBy("title")` and then you request key-based pagination based on `_Book.isbn`, which is equivalent to `order by title, isbn` in SQL, and then you apply the restriction `isbn>lastPageIsbn`, you get back well-defined pages? To me it seems like the order by `title` would break that.

The restriction for keyset cursor-based pagination here with the two sort criteria and two keyset values would be `(title > lastPageTitle) OR (title == lastPageTitle AND isbn > lastPageIsbn)`.  Hopefully I wrote that correctly. They are sometimes hard to think about which is why it's nice to have the Jakarta Data provider doing it all for you.  I think we have some longer examples somewhere in the spec or KeysetAwarePage JavaDoc as well.

**Comment by njr-11** [comment]
> Or do you automatically add the `title` to the restriction and to the `Cursor`?

yes

**Comment by gavinking** [comment]
Wait, is it the intention that keys are usually determined _implicitly_ from the query method?

**Comment by gavinking** [comment]
For some reason I had picked up the opposite impression, that the `Cursor` was completely determined by the sorting criteria attached to the `PageRequest`. But now I'm not quite sure why I thought that.

Anyway if it's not stated explicitly somewhere, it should be.

**Comment by gavinking** [comment]
I think it's because of the _extremely_ tight relationship between Cursor and PageRequest. It's at least a bit unexpected that two fields of the same object "disagree" on what the key is.

**Comment by njr-11** [comment]
> For some reason I had picked up the opposite impression, that the `Cursor` was completely determined by the sorting criteria attached to the `PageRequest`. But now I'm not quite sure why I thought that.

The combined Sort criteria (and precedence for sorting) from the entire repository method is what to use for determining which entity attributes make up the keyset cursor.  As for the values, there are a couple of patterns available. One is where a user explicitly specifies values for the keyset cursor (which had better match the combined sort criteria, otherwise raise an error back to them).  Another is where the user obtains the cursor from an existing page.  And the other, which is similar, is where the user asks for the next or previous page and doesn't need to directly access the cursor.

**Comment by njr-11** [comment]
This is what is currently in the JavaDoc,
```
 This list of values is referred to as the keyset
 * and consists of the values of entity properties that are in the sort criteria
 * of the repository method. The combination of sort criteria must uniquely
 * identify each entity.
```

**Comment by njr-11** [comment]
I wasn't meaning to say the current documentation is good enough, just to cite what is already written so we can decide where to improve it.

I can look into adding further explanation of this in the specification document after the part where it states:

```
The sort criteria for a repository method that performs keyset pagination must uniquely identify each entity and must be provided by:

    OrderBy name pattern of the repository method (as in the examples above) or @OrderBy annotation(s) on the repository method.

    Sort parameters of the PageRequest that is supplied to the repository method.
```
That seems like a good lead in to the topic.
