### ISSUE TITLE
Additional POM details

### ISSUE THREAD

**Issue by sebersole** [jakartaee/data#529]
### Specification Version

1.0.0-M3

### Bug report

More of a request than a bug, but there is no such label... 

Currently the published POM is missing certain metadata that is generally useful for users - based on https://jakarta.oss.sonatype.org/content/repositories/snapshots/jakarta/data/jakarta.data-api/1.0.0-SNAPSHOT/jakarta.data-api-1.0.0-20231118.185417-1.pom.  

* Source control link (although I noticed that `<scm/>` is defined in the source POM, so not exactly sure why that is not in the published form)
* Issue tracker link
* License

**Comment by KyleAure** [comment]
The snapshot version linked in this issue is very old. 
The [latest snapshot](https://jakarta.oss.sonatype.org/content/repositories/snapshots/jakarta/data/jakarta.data-parent/1.0.0-SNAPSHOT/jakarta.data-parent-1.0.0-20240407.041108-55.pom) has most of this information except IssueManagement.
Will close once issueManagement is added.
