### ISSUE TITLE
Coupling Pageable with Sort [Vote]

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#54]
At the PR https://github.com/jakartaee/data/pull/37

We discussed whether ```Pageable``` should have a tight coupling with ```Sort```.

There is no discussion about ```Sort``` being usable standalone.

Both decisions have a trade-off; 

The discussion link:

https://github.com/jakartaee/data/pull/37#discussion_r1001923342

## Vote

* Decoupling Pageable with Sort
* Keep coupling Pageable and Sort
* Another option

**Comment by njr-11** [comment]
To help illustrate the trade-offs, here are examples with both.  _Sort Decoupled from Pageable_ eliminates some error paths (5, 10) and a confusing pattern (6).  _Pageable that includes Sort_ is better for requesting next pages (9) and it is consistent with existing implementations (11).

1. OrderBy in method name - Sorting without pagination.
Same for both:
`List<Person> found = people.findByAgeOrderByLastNameAscFirstNameAsc(40);`

2. OrderBy in method name - Obtaining first page.
Same for both:
`Page<Person> page1 = people.findByAgeOrderByLastNameAscFirstNameAsc(40, Pageable.size(50));`

3. OrderBy in method name - Obtaining next page.
Same for both:
`Page<Person> page2 = people.findByAgeOrderByLastNameAscFirstNameAsc(40, page1.nextPageable());`

4. OrderBy in method name and Sort on repository method (Error Path)
Same for both:
`err = people.findByAgeOrderByLastNameAsc(40, Pageable.size(50), Sort.asc("firstName"));`

5. OrderBy in method name and Sort in Pageable (Error Path)
Sort decoupled from Pageable:
`API does not permit this error path`
Pageable that includes Sort:
`err = people.findByAgeOrderByLastNameAsc(40, Pageable.of(1, 50, Sort.asc("firstName"));`

6. OrderBy in method name, Obtaining Sorts from Pageable
Sort decoupled from Pageable:
`API does not permit this confusing pattern`
Pageable that includes Sort:
`page = people.findByAgeOrderByLastNameAsc(40, Pageable.of(50));`
`? = page.nextPageable().getSorts();`
`? = page.getPageable().getSorts();`

7. Sorts - Sorting without pagination.
Same for both:
`List<Person> found = people.findByAge(40, Sort.asc("lastName"), Sort.asc("firstName"));`

8. Sorts - Obtaining first page.
Sort decoupled from Pageable:
`page1 = people.findByAge(40, Pageable.size(50), Sort.asc("lastName"), Sort.asc("firstName"));`
Pageable that includes Sort:
`page1 = people.findByAge(40, Pageable.of(1, 50, Sort.asc("lastName"), Sort.asc("firstName")));`

9. Sorts - Obtaining next page.
Sort decoupled from Pageable:
`page2 = people.findByAge(40, page1.nextPageable(), Sort.asc("lastName"), Sort.asc("firstName"));`
Pageable that includes Sort:
`page2 = people.findByAge(40, page1.nextPageable());`

10. Sort in Pageable and as repository parameter (Error path)
Sort decoupled from Pageable:
`API does not permit this error path`
Pageable that includes Sort:
`err = people.findByAge(40, Pageable.of(1, 50, Sort.asc("lastName")), Sort.asc("firstName"));`

11. Consistency with existing implementations.
Sort decoupled from Pageable:
`different from existing implementations`
Pageable that includes Sort:
`matches what existing implementations have done`

**Comment by njr-11** [comment]
What I would vote for this all depends on item 9 above.

Forcing users to re-specify the sort criteria on each subsequent page request is redundant and error prone. We should avoid this in the programming model:
`page1 = people.findByAge(40, Pageable.size(50), Sort.asc("lastName"), Sort.asc("firstName"));`
`page2 = people.findByAge(40, page1.nextPageable(), Sort.asc("lastName"), Sort.asc("firstName"));`

Including the sort criteria within the Pageable is one way to achieve that:
`page1 = people.findByAge(40, Pageable.of(1, 50, Sort.asc("lastName"), Sort.asc("firstName")));`
`page2 = people.findByAge(40, page1.nextPageable());`

The other way that I can think of is adding `.next()` to Pageable:
`page1 = people.findByAge(40, Pageable.size(50), Sort.asc("lastName"), Sort.asc("firstName"));`
`page2 = page1.next();`

I know at least one specification participant didn't like the idea of having a `Page.next()` because it means a Page represents more than just the query results, it would also require awareness of the query that requested it. However, when we start to look at computation of `Page.getTotalPages()` and `Page.getTotalElements()`, it seems to me that decision is going to cause inefficiency in querying.  Ideally, the total number of entities across all pages would be computed once only and not recomputed with every page. However, we need to consider that for the following pattern that the request for initial page and subsuquent page are identical from the standpoint of the repository implementation in that both accept a Pageable and only the user knows whether it's an initial vs subsequent page request:

`page1 = people.findByAge(40, Pageable.of(1, 50, Sort.asc("lastName"), Sort.asc("firstName")));`
`page2 = people.findByAge(40, page1.nextPageable());`

Having a `page.next()` would not only be more convenient to the user, it would also capture the information to distinguish subsequent page requests from the initial, making it possible for repositories to more efficiently avoid re-obtaining the total count on every subsequent page.

I think we need to first (re)consider `Page.next()` and after that it will be possible to better assess coupling for Pageable and Sort.
