### ISSUE TITLE
Clarification Requested on `CursoredPage` Interface Regarding Cursor Management[clarification]: 

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#558]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc

### I need clarification on ...

The `CursoredPage` interface method `PageRequest.Cursor cursor(int index);` raises questions about the number of Cursors that we have. The documentation provides an example of obtaining a single cursor but does not address handling multiple cursors.

```java
PageRequest<Employee> pageRequest = PageRequest.of(Employee.class).size(50).afterKey(emp.lastName, emp.firstName, emp.id);
PageRequest.Cursor cursor = pageRequest.cursor().orElseThrow();
```

If we can only have a single Cursor, why should we have a method that returns a Cursor-based index?

The solution proposal updates the method returning a single cursor and the getIndex method:

```java
PageRequest.Cursor cursor();
//like the cursor interface
Object get(int index);

```

**Comment by gavinking** [comment]
I have been informed by @beikov that it is useful to be able to obtain the cursor of an arbitrary row. I don’t have a good understanding of why, however.

**Comment by njr-11** [comment]
> The documentation provides an example of obtaining a single cursor but does not address handling multiple cursors.
> 
> ```java
> PageRequest<Employee> pageRequest = PageRequest.of(Employee.class).size(50).afterKey(emp.lastName, emp.firstName, emp.id);
> PageRequest.Cursor cursor = pageRequest.cursor().orElseThrow();
> ```
> 
> If we can only have a single Cursor, why should we have a method that returns a Cursor-based index?

Could you cite where in the specification you found that example which you are asking about?  The second line looks very wrong but I cannot find it anywhere in the spec or JavaDoc,

```java
PageRequest.Cursor cursor = pageRequest.cursor().orElseThrow();
```

It is not true that you can only have a single cursor. The most useful cursors are typically the ones at the beginning and end of a page, relative to which the previous and next pages are obtained.

**Comment by otaviojava** [comment]
> Could you cite where in the specification you found that example which you are asking about? The second line looks very wrong but I cannot find it anywhere in the spec or JavaDoc,

The code itself returns an Optional, here at the [PageRequest](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/page/PageRequest.java#L263) if it allows multiple cursors, it should be a List instead, isn't?

**Comment by njr-11** [comment]
> The code itself returns an Optional, here at the [PageRequest](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/page/PageRequest.java#L263) if it allows multiple cursors, it should be a List instead, isn't?

From that I can gather that you didn't copy that code example out of the specification or JavaDoc at all and you just wrote it yourself.  I'm glad to see we didn't write that combination of lines into any of our examples because it's an inefficient way to get a Cursor.  Note that you can create new Cursor instance with just,

```java
Cursor cursor = Cursor.forKey(emp.lastName, emp.firstName, emp.id);
```

You can create multiple if you want.

If you want to know what `pageRequest.cursor()` is for, its purpose is to return the cursor relative to which to request the page.  A page request is relative to one cursor (or none if offset-based rather than cursor-based).  Once you have a page, you can create a cursor from any position on that page.

**Comment by beikov** [comment]
For completeness, we discussed that it is nice to be able to access all cursors so that one can implement e.g. the [GraphQL Relay specification](https://relay.dev/docs/guides/graphql-server-specification/) with this. I don't quite understand why it is necessary to have a cursor for each edge, but that's how the schema is designed.

Since acquiring cursors is usually done through additional select items in e.g. SQL, the query result will have all cursor instances anyway, so I thought there is not much overhead if we allow access to all cursors. The idea of not exposing a list is to avoid materializing the cursor objects eagerly if not needed.

**Comment by gavinking** [comment]
> Since acquiring cursors is usually done through additional select items in e.g. SQL, the query result will have all cursor instances anyway, so I thought there is not much overhead if we allow access to all cursors.

Indeed.
