### ISSUE TITLE
Repositories types that we'll have support

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#8]
I'm creating this thread to discuss which repositories we should support, at least in this first version of Jakarta Data.

When I checked the Java solutions broadly spread in the market, I usually saw **three repositories types**:

## **CrudOperation**

Interface to generic CRUD operations on a repository for a specific type. This one we can see more often on several Java implementations.

*E.g.:* 

-  [CrudRepository](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/CrudRepository.java) by Spring
- [CrudRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/CrudRepository.java) by Micronaut
- [Repository](https://github.com/eclipse-ee4j/nosql/blob/main/api/mapping/mapping-core/src/main/java/jakarta/nosql/mapping/Repository.java) by Jakarta NoSQL
- [EntityRepository](https://github.com/apache/deltaspike/blob/master/deltaspike/modules/data/api/src/main/java/org/apache/deltaspike/data/api/EntityRepository.java) by Delta Spike
- [PanacheRepository](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/PanacheRepository.java) by Quarkus

## Paging

Interface with generic CRUD operations using the pagination feature.

*E.g.:* 

- [PagingAndSortingRepository](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/PagingAndSortingRepository.java) by Spring
- [PageableRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/PageableRepository.java) by Micronaut
- [Repository](https://www.jnosql.org/spec/#_repository_2) by Jakarta NoSQL

## Reactive

Interface for generic CRUD operations on a repository for a specific type. This repository follows reactive paradigms.

*E.g.:* 

- [ReactiveStreamsCrudRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/reactive/ReactiveStreamsCrudRepository.java) and [ReactiveStreamsPageableRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/reactive/ReactiveStreamsPageableRepository.java) by Micronaut
- [ReactiveCrudRepository](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/reactive/ReactiveCrudRepository.java) and [ReactiveSortingRepository](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/reactive/ReactiveSortingRepository.java) by Spring
- [ReactiveRepository](https://github.com/eclipse/jnosql/blob/main/jnosql-mapping/jnosql-mapping-reactive/jnosql-mapping-reactive-core/src/main/java/org/eclipse/jnosql/mapping/reactive/ReactiveRepository.java) by Jakarta NoSQL/JNoSQL

Should we follow support those types as well?

We won't discuss the how on this thread but only the repositories types that we should have support on Jakarta Data.

**Comment by frowe** [comment]
I don't see PageableRepository i/f in JNoSQL?

**Comment by frowe** [comment]
ah, ok, so not a separate interface.

**Comment by otaviojava** [comment]
@keilw about Reactive, 
Reactive Streams = The interfaces available in JDK >= 9.
On Java 11, it has those interfaces: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/Flow.html

**Comment by keilw** [comment]
@otaviojava Then which are the repository extensions in Spring, Micronaut etc. that use nothing but the JDK?

**Comment by dstepanov** [comment]
We should probably define the supported format of the methods like save, update, find etc., and supported return types, which can include the reactive/async type, and by that define a reactive/async method. Repositories are just subsets of those methods.

**Comment by keilw** [comment]
The problem is, that save, update, find, etc. of each "Reactive*" repository in Spring, Micronaut or others look totally incompatible with each other.
`<S extends T> Mono<S> save(S entity); ` returns a Reactor [Mono](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html) which does not even use any interfaces from the JDK, so it's incompatible with all the others.
[ReactiveRepository](https://github.com/eclipse/jnosql/blob/main/jnosql-mapping/jnosql-mapping-reactive/jnosql-mapping-reactive-core/src/main/java/org/eclipse/jnosql/mapping/reactive/ReactiveRepository.java) is part of JNoSQL and I think that's just the right place. Even Reactive Streams does not seem to use the JDK `Flow` yet, and with very few exceptions, the JDK being more a Reference Implementation itself is not so good at defining abstract APIs and specs that other projects use (just remember **Java Util Logging**) so unless @graemerocher or @dstepanov can show common denominators of
- [RxJavaCrudRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/reactive/RxJavaCrudRepository.java)
- [ReactiveStreamsCrudRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/reactive/ReactiveStreamsCrudRepository.java)
that would fit into a `GenericReactiveInterface` or similar, there may be no real abstraction possible (yet) and all those better be left to **compatible implementations**.

In fact the totally different structures, entity and return types for each of these reactive or otherwise "new and fancy" extensions to the repository interface is why we probably should have the most basic "tagging interface" like Spring's `Repository` or Micronaut's `GenericRepository` because it would be compatible on the most abstract level with reactive extensions while they cannot extend the respective `CrudRepository` types in either Spring or Micronaut.

**Comment by otaviojava** [comment]
@keilw JNoSQL uses a [Observable](https://github.com/eclipse/jnosql/blob/main/jnosql-mapping/jnosql-mapping-reactive/jnosql-mapping-reactive-core/src/main/java/org/eclipse/jnosql/mapping/reactive/Observable.java) based on reactivestreams as Microstream does.

**Comment by graemerocher** [comment]
One comment. I don't think `CrudRepository` and `PageableRepository` should be unified into a single interfaces. Some backing databases don't support paging so it doesn't make sense to do so IMO.

If we were to support Reactive then the way to do that would be the `Flow` API for sure. There are bridges and adapters 2 and from `Flow` which implementations could use.

**Comment by otaviojava** [comment]
So, we'll have DataRepository as a parent and the other specializations: 
```mermaid
graph TD;
    DataRepository-->CrudOperation;
    DataRepository-->PageableRepository;
    DataRepository-->ReactiveRepository;
```

**Comment by keilw** [comment]
Whxy is there a `CrudOperation` instead of `CrudRepository`?

**Comment by graemerocher** [comment]
`FlowRepository` is fine too
