### ISSUE TITLE
Should we have the OrderBy annotation?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#94]
To sort any data using the Repository feature at Jakarta Data, we have three ways:

1.  Using the `Pageable` or `Sort`to makes it possible dynamically
2. The method by query through the `order by  in the method statically
3. Using the `Sort` annotation statically.

My question: Do we need Sort annotation? I guess one to each, dynamically and statically, is enough.

**Comment by njr-11** [comment]
If we need to get rid of one (and I'm not sure that we do), I would vote for getting rid of the `...OrderBySomethingAscSomethingElseAscAnotherThingAsc` in the method name.  It makes for methods that are difficult to read and consume in code, whereas the other mechanisms, including the annotation are much cleaner and more readable.

**Comment by mp911de** [comment]
No, you should not have a sort annotation.

Consider the following:

```java

@Sort(by="baz")
List findByFooOrderBySomething()
```

An annotation creates easily ambiguity because it stands in front of the method.

While a `Sort` argument indicates sort appending:

```java
List findByFooOrderBySomething(Sort sort)
```

**Comment by njr-11** [comment]
> An annotation creates easily ambiguity because it stands in front of the method.
> 
> While a `Sort` argument indicates sort appending:
> 
> ```java
> List findByFooOrderBySomething(Sort sort)
> ```

Allowing the same capability to be specified in 2 different places on the same method is a cause of ambiguity regardless of whether it comes from an annotation, a method name, or wherever.  The order/position of each does not imply an intuitive behavior and we should raise an error for the conflict, which is what the Jakarta Data spec currently defines:

In `Sort`,
https://github.com/jakartaee/data/blob/f0888ead734aca15ef442c979185318845f0a722/api/src/main/java/jakarta/data/repository/Sort.java#L44-L50

and `@OrderBy`,
https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/repository/OrderBy.java#L50-L56

and `Pageable`,
https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/repository/Pageable.java#L240-L248

The first 2 above are lacking mention of the conflict with `Sort` that comes from a `Pageable` which was missed when `Sort` was added to `Pageable`.  I've added pull #95 to correct that.

**Comment by amoscatelli** [comment]
> If we need to get rid of one (and I'm not sure that we do), I would vote for getting rid of the `...OrderBySomethingAscSomethingElseAscAnotherThingAsc` in the method name. It makes for methods that are difficult to read and consume in code, whereas the other mechanisms, including the annotation are much cleaner and more readable.

I think the Annotation approach is much better than the method name one for the same reasons.
Also Annotation approach can be used with Metadata to be even less prone error ...

The same applies for the fields to retrieve ...

**Comment by mp911de** [comment]
In the context of pagination, the sort annotation creates ambiguity again:

```
@Sort(by=Product_.PRICE)
List<Product> findProducts(
   @Field(name=Product_.CODE) String code,
   @Field(name=Product_.PROVIDER) String provider,
   Pageable pageRequest
)
```

Which of the components takes precedence? The sort annotation or the sort from `Pageable`? Also, we are past the point of string-based programming. Components of a domain model should not be expressed as strings because they are easy to miss.

**Comment by amoscatelli** [comment]
What do you mean by "we are past the point of string-based programming" ?

I think the taking account of field names parsed directly by the method name is the easiest thing to miss (think of a refactor for example).

Metadata main purpose is the to NOT be easy to miss !
Also, mine was just an example, something like SingularAttribute could also be used instead of strings.

Imho if you use a Pageable parameter, this should take precedence and the Sort annotation is the default sorting.

**Comment by njr-11** [comment]
> In the context of pagination, the sort annotation creates ambiguity again

Currently there is no ambiguity. The specification currently says it's an error to specify sort in conflicting ways on the same method. And in any case conflicts involving the annotation are no worse than conflicts with the other mechanisms: the `OrderBy` method name pattern or the `Sort` parameter,

Conflict between `Pageable.sorts` and `Sort` method parameter:
```
Pageable pagination = Pageable.ofSize(10).sortBy(Sort.asc("price"));
products.findByPriceBetween(min, max, pagination, Sort.desc("price"));
```

Conflict between 'OrderBy` in method name and `Sort` method parameter:
```
products.findByPriceBetweenOrderByPriceDesc(min, max, pagination, Sort.asc("price"));
```

Conflict between `OrderBy` in method name and `Pageable.sorts` parameter:
```
Pageable pagination = Pageable.ofSize(10).sortBy(Sort.asc("price"));
products.findByPriceBetweenOrderByPriceDesc(min, max, pagination);
```

The specification currently states the conflict is an error, but we could change it to define a precedence instead as is being discussed.  If we do that, I like what @amoscatelli suggests for giving `Pageable` precedence,

> Imho if you use a Pageable parameter, this should take precedence and the Sort annotation is the default sorting.

because it seems the most useful that the more flexible mechanism that is computed at run time would be able to override.  Code that leverages the override is also more readable with the combination of annotation + Pageable than it is with the combination of `OrderByPriceDesc` + Pageable because the latter combination forces the user to type in `OrderByPriceDesc` as part of a method name that could end up doing the opposite (due to the override) of what its name says it will do.

**Comment by njr-11** [comment]
> Also Annotation approach can be used with Metadata to be even less prone error ...
> 
> The same should/could be applied for the fields to filter with :
> 
> ```
> @Filter(by={ Product_.CODE, Product_.PROVIDER} )
> @Sort(by=Product_.PRICE)
> List<Product> findProducts(String code, String provider)
> ```

I really like this idea and believe is worth exploring further.  I'm opening a new issue #94 that we can devote entirely to it.

**Comment by mp911de** [comment]
One of the key points of derived query methods is that a method name reflects the query structure. Along with its signature, that's all one needs to know when developing an application. Moving filters and sorting into the declaration site removes useful information during development time (e.g. code completion shows only names and signatures) and therefore, such an approach removes a lot of what makes repository query methods useful.

**Comment by amoscatelli** [comment]
I think that the key point should be the delivery of query methods without really provide an implementation in a stable, powerful, safe and less error prone way.
Anyway what I am suggesting does not exclude the possibility to choose the method name you prefer. You can still use the full method name if you think it suits you better. At last, Javadoc is showed in code completion.

For sure as a developer I would surely pick the annotation road.

**Comment by amoscatelli** [comment]
Also, allowing decoupling method names and method logic can be useful to migrate legacy code to adopt this spec without refactoring.

**Comment by amoscatelli** [comment]
I double checked and Annotations too are showed in autocompletion, at least with Netbeans 16 : 

![image](https://user-images.githubusercontent.com/16684470/212027444-146db27b-e483-494e-b039-50ab6038e984.png)

**Comment by otaviojava** [comment]
Returning from the `Sort`annotation.

Do we have any success cases about this annotation or similar in the industry, such as Micronaut or Spring Data?

I don't think so, thus, I believe removing this annotation is a good step to at least the first version.

Please, let me know your thoughts!

**Comment by odrotbohm** [comment]
I'd vote to avoid the additional annotation, as it blurs the different declaration models: either you derive the static parts of the query from the method name entirely, *or* you completely declare it in the `@Query` annotation. Mixing the approaches is just adding confusion without solving a problem that cannot be solved with the already established mechanisms.

One other thing you have to consider is that there already is a `Sort` type to be used as parameter. Every repository declaration that would want to use both the parameter type and the annotation would end up having to fully qualify one of the imports, which looks ugly.

**Comment by njr-11** [comment]
> One other thing you have to consider is that there already is a `Sort` type to be used as parameter. Every repository declaration that would want to use both the parameter type and the annotation would end up having to fully qualify one of the imports, which looks ugly.

Some clarification is needed here - Although the discussion in the issue keeps referring to it as a sort annotation, the annotation that we currently have in the spec is not named `@Sort`; it is named `@OrderBy`, which means we do not currently have an issue with name collisions or a need for fully qualifying.

**Comment by otaviojava** [comment]
@njr-11, my bad I fixed it.
But the @odrotbohm paragraph still makes a good point, mainly on this point:

> If we care about the adoption of the API, we might wanna make sure that it stays as close as possible to the established abstractions like Spring Data, Micronaut et al. Any move away from those subverts that goal. Plus, it decreases the chance that the existing implementations even consider implementing the spec.

I will be more comfortable if we remove it and push it again when we have more implementation cases.

**Comment by njr-11** [comment]
Spring and Micronaut already have already implemented static sort critera and have proven the concept to be useful. This doesn't change any of that and it doesn't subvert their implementations. We aren't defining incompatible behavior here. We're specifying the same behavior, with some improved usability on how you can ask for it. If anything, this should make it more likely for developers to use Spring and Micronaut. Whenever I present Jakarta Data I get feedback from developers that they wouldn't want to use the `OrderBy` keyword pattern because it makes method names too long and difficult to use and understand in code. The `@OrderBy` annotation solves that problem with a cleaner way to designate that you want static sorting. It also has benefits when it comes to keyset pagination, enabling static sort for custom queries in the same way you can append dynamic sort for custom queries.

**Comment by otaviojava** [comment]
@njr-11 

It was not my question.

I'm not saying to remove forever, but follow this methodology:

* Remove from spec
* Show it on at least two implementation
* Propose again, but with more cases from those implementations/vendors.

**Comment by njr-11** [comment]
It's a usability improvement when requesting sort criteria statically, not new function that needs to be proven.  Multiple implementations have already proven it with the `OrderBy` keyword.

**Comment by otaviojava** [comment]
@njr-11 could you show us?

**Comment by njr-11** [comment]
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-creation
https://micronaut-projects.github.io/micronaut-data/latest/guide/index.html#ordering
https://deltaspike.apache.org/documentation/data.html#QueryOrdering

**Comment by otaviojava** [comment]
We're talking about the `Orderby` as an annotation, isn't it?

**Comment by njr-11** [comment]
Yes, `@OrderBy` is the usability improvement that the Jakarta Data spec made to how you can provide sort criteria statically, and the `OrderBy` keyword which is already in use demonstrates provision of sort criteria statically.

**Comment by odrotbohm** [comment]
Whether the annotation actually is a usability improvement is discussed here, and we currently don't have any data points that support this assumption, except presentations that present this as a potential feature. Who doesn't like a faster horse? At least if you don't have to feed it.

> Whenever I present Jakarta Data I get feedback from developers that they wouldn't want to use the OrderBy keyword pattern because it makes method names too long and difficult to use and understand in code.

That feels like a very particular view because all the selection criteria encoded in the method name also substantially add to the method name's length. If that length becomes a concern, the general recommendation is to move *all* of it into a `@Query` annotation. It's not immediately obvious why the order by clause is singled out for special treatment (a separate annotation) and everything else isn't.

Also, you completely seem to disregard the cognitive load that multiple options offered to achieve the same result has on developers. The ones currently available in existing implementations at least have clear guiding rules attached to them (as mentioned above). Assuming you add a new way of declaring order, just try to clearly describe, what the rules are when you would recommend applying which option. If that explanation is more complex than the one without that additional option, and you're not covering an additional real-world use case, the net cognitive effect of the addition is negative and – IMO – should be avoided.

**Comment by njr-11** [comment]
I would say that requiring someone to learn JPQL and use `@Query` (and lose the ability to combine with dynamic sort, and lose the ability to do keyset pagination) because the `OrderBy` query-by-method pattern has made method names so long they become unusable is the wrong answer.  We already have an excellent solution to this in the `@OrderBy` annotation, if we just don't remove it.

If cognitive overload is a concern here, I'd start by ranking the 5 options for specifying sort criteria from most useful to least:

1. `Sort` parameters to repository method
2. `@OrderBy` annotation
3. Allowing `ORDER BY` on `@Query` where it doesn't conflict with others
4. `Sort` parameters to `Pageable`
5. `OrderBy` keyword in method name

We can cover everything in the spec for dynamic/static/custom patterns with just the first 3. We could not do so with only the bottom 3.  Item 4 is a convenience because it spares the user from needing to specify the same Sort list every time they request a page.  The only value I can see in item 5 is having better compatibility with existing implementations, which is fine.  It seems like a reasonable compromise to me that we leave them all in the spec. Yes, there's some degree of overload, but it doesn't seem that we can all come to agreement on what the right thing is to remove, and at least this way everyone can choose the approach they prefer.

**Comment by otaviojava** [comment]
As Oliver said:

> Whether the annotation actually is a usability improvement is discussed here, and we currently don't have any data points that support this assumption, except presentations that present this as a potential feature. Who doesn't like a faster horse? At least if you don't have to feed it.

I am still missing data about this point.

**Comment by njr-11** [comment]
We can certainly collect data on it over the next year if both options remain in spec betas over that time.  If you take either of them out, then you'll no longer have a fair comparison because of course users will have a bias for whatever they find in the specification/javadoc betas over extra vendor-specific stuff.

**Comment by otaviojava** [comment]
@njr-11, my recommendation would move the spec forward, removing this annotation while you can test it on the oper-liberty side and give us feedback for the next spec version.

**Comment by mswatosh** [comment]
> Whether the annotation actually is a usability improvement is discussed here, and we currently don't have any data points that support this assumption, except presentations that present this as a potential feature

There's quite a bit of data pointing to users looking to shorten method names:

https://stackoverflow.com/questions/30019408/how-to-shorten-names-of-query-methods-in-spring-data-jpa-repositories
https://stackoverflow.com/questions/39163466/is-there-any-anotation-to-make-a-spring-data-repositories-method-names-shorter
https://stackoverflow.com/questions/58050904/method-names-too-long-in-spring-jpa

And even someone calling out this specific case, where their recommendation if OrderBy starts to make the method name too long is to switch to `Sort` on the `Pageable`. The OrderBy annotation could fix this while keeping the ordering obvious for static ordering.
https://stackoverflow.com/questions/25486583/how-to-use-orderby-with-findall-in-spring-data#comment109173512_27427359

Personally, I like that it gives the ability to cleanly separate _What_ data you want from _How_ you want it.

**Comment by mswatosh** [comment]
>Long method names are a symptom of unintended usage.

It's clear from the Spring Data docs how Spring Data is intended to be used, but when have users ever restricted themselves to our intended use cases? :-)

>I do not understand the entire discussion about trying to come up with new ideas that haven't proved to be useful in practice. 

If I look at other Jakarta repos I see open issues with suggestions for ways to improve the spec, few of which seem to be implemented and therefore proven useful. Isn't our goal here to discuss ideas that may be useful to users? There are valid reasons to not include new ideas in a spec, but I don't believe that it not being in an existing implementation is one of them.

>Instead, such optimizations should be explored within implementations.

This is directly counter to:

>switching implementations was all but smooth because of implementation-specific quirks.

One of the goals of Jakarta EE is portability, so even if you don't believe users are likely to change stacks, suggesting that each implementation add implementation-specific quirks is not a good solution. If each implementation adds it's own quirks, then implementations are more likely to push for their own quirks to be included in the spec, which may be detrimental to the specs progress.

If every enhancement to the spec is going to be seen by the implementations that existed prior as not worth the effort to implement, then Jakarta Data will only ever be a 1.0 version of the least common denominator between Deltaspike, Spring, and Micronaut.

Back to the discussion of the OrderBy annotation,
>Query methods are designed to express how data is being filtered and sorted.

The annotation provides a clean way to separate how the data is filtered from how it's sorted. Open Liberty users and Spring Data users would both take advantage of it with long query name, which we know the have, that's why I think it's worth keeping in the spec.
